name: mrmerch

profile: mrmerch

version: '1.0'

require-dbt-version: ">=0.16.1"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
  transient: true
