name: mrmerch

profile: mrmerch

version: '1.0'

require-dbt-version: ">=0.15.0"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

quoting:
  database: true
  identifier: true
  schema: true

models:
  transient: true
  
  quickbooks:
    enabled: true
    materialized: view
    tables:
      materialized: table
      quickbooks_general_ledger:
        dist: id
        sort: txn_date
    base:
      materialized: ephemeral

    vars:
      "base.accounts"                     : "raw.qbo.quickbooks_accounts"
      "base.bills_line"                   : "raw.qbo.quickbooks_bills__line"
      "base.billpayments"                 : "raw.qbo.quickbooks_billpayments"
      "base.billpayments_line"            : "raw.qbo.quickbooks_billpayments__line"
      "base.billpayments_line__linkedtxn" : "raw.qbo.quickbooks_billpayments__line__linkedtxn"
      "base.bills"                        : "raw.qbo.quickbooks_bills"
      "base.classes"                      : "raw.qbo.quickbooks_classes"
      "base.customers"                    : "raw.qbo.quickbooks_customers"
      "base.deposits_line"                : "raw.qbo.quickbooks_deposits__line"
      "base.deposits_line_linkedtxn"      : "raw.qbo.quickbooks_deposits__line__linkedtxn"
      "base.deposits"                     : "raw.qbo.quickbooks_deposits"
      "base.invoices_lines"               : "raw.qbo.quickbooks_invoices__line"
      "base.invoices"                     : "raw.qbo.quickbooks_invoices"
      "base.items"                        : "raw.qbo.quickbooks_items"
      "base.journal_entries"              : "raw.qbo.quickbooks_journalentries"
      "base.journal_entries_line"         : "raw.qbo.quickbooks_journalentries__line"
      "base.payments"                     : "raw.qbo.quickbooks_payments"
      "base.purchases_line"               : "raw.qbo.quickbooks_purchases__line"
      "base.purchases"                    : "raw.qbo.quickbooks_purchases"
      "base.vendors"                      : "raw.qbo.quickbooks_vendors"
      "level_0_id_field"                  : "_sdc_level_0_id"
      "source_key_id_field"               : "_sdc_source_key_id"

on-run-end:
  - "{{ grant_select_on_schemas(schemas, 'reporter') }}"
  - "{{ grant_select_on_schemas(schemas, 'transformer') }}"
